model:
  encoder:
    type: resnet50
    pretrained: true
    embed_nim: 512
  decoder:
    type: transformer
    num_layers: 6
    num_heads: 8
    embed_nim: 512
    ff_dim: 2048
    dropout: 0.1
  sos_token: "<start>"
  eos_token: "<end>"
  pad_token: "<pad>"

training:
  batch_size: 64
  num_workers: 4
  epochs: 30
  learning_rate: 0.0001
  optimizer: adam
  weight_decay: 0.0005
  schedule:
    type: cosine
    warmup_steps: 1000
  loss: cross_entropy
  device: "cuda"

logging:
  log_dir: ./log
  save_checkpoint: true
  checkpoint_dir: ./dir
  save_every: 5
  eval_every: 1
